import { expect, test } from '@playwright/test'

test('Linha Ouro inclui Congonhas e Washington Luís sem ativar projetos', async ({ page }) => {
  await page.goto('/')
  const map = page.locator('svg[role="img"]')
  await expect(map.getByRole('button', { name: 'Estação Aeroporto de Congonhas', exact: true })).toBeAttached()
  await expect(map.getByRole('button', { name: 'Estação Washington Luís', exact: true })).toBeAttached()
  await expect(map.getByRole('button', { name: 'Estação Paraisópolis', exact: true })).toHaveCount(0)
})

test('Ouro desenha ramais separados e identifica a integração Morumbi–Linha 9', async ({ page }, testInfo) => {
  await page.goto('/')
  const gold = page.locator('svg').getByRole('button', { name: 'Linha Linha 17–Ouro', exact: true })
  // Three separate operating paths: common trunk and the two branches.
  await expect(gold.locator('path[opacity]')).toHaveCount(3)
  await expect(gold.locator('path[stroke-dasharray]')).toHaveCount(0)
  await page.getByRole('button', { name: 'Linhas', exact: true }).click()
  await page.getByRole('button', { name: /^17 Ouro/ }).click()
  const panel = page.getByRole('dialog')
  await expect(panel).toContainText('8 em operação · 10 previstas')
  await expect(panel).toContainText('Morumbi ↔ Aeroporto de Congonhas / Washington Luís')
  if (testInfo.project.name !== 'desktop') await page.getByRole('button', { name: 'Ver detalhes', exact: true }).click()
  await expect(panel.getByRole('heading', { name: 'Ramal Aeroporto de Congonhas', exact: true })).toBeVisible()
  await expect(panel.getByRole('heading', { name: 'Ramal Washington Luís', exact: true })).toBeVisible()
  const morumbi = panel.getByRole('button', { name: 'Ver estação Morumbi', exact: true }).first()
  await expect(morumbi).toContainText('9')
  await morumbi.click()
  await expect(panel.getByRole('button', { name: /9.*Esmeralda/ })).toBeVisible()
  await expect(panel.getByRole('button', { name: /17.*Ouro/ })).toBeVisible()
  await page.getByRole('button', { name: 'Fechar', exact: true }).click()
  await page.getByRole('button', { name: 'Diagrama', exact: true }).click()
  await expect(gold.locator('path[opacity]')).toHaveCount(3)
  await page.getByRole('button', { name: 'Exibição', exact: true }).click()
  await page.getByRole('checkbox', { name: /Em estudo/ }).check()
  await page.keyboard.press('Escape')
  await expect(gold.locator('path[stroke-dasharray="1 10"]')).toHaveCount(2)
  await expect(gold.locator('path[opacity]:not([stroke-dasharray])')).toHaveCount(3)
  await page.screenshot({ path: testInfo.outputPath('ouro-projetos.png') })
})
