import { expect, test } from '@playwright/test'

test('percurso mostra conexões e abre a estação com ação de mapa', async ({ page }, testInfo) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Linhas', exact: true }).click()
  const entries = page.locator('#line-list li button')
  await expect(entries.nth(0)).toContainText('Azul')
  await expect(entries.nth(3)).toContainText('Amarela')
  await expect(entries.nth(4)).toContainText('Lilás')
  await expect(entries.nth(0)).toContainText('Em operação')
  await page.screenshot({ path: testInfo.outputPath('lista-linhas.png') })
  await entries.nth(0).click()
  const dialog = page.getByRole('dialog')
  await expect(dialog).toHaveAttribute('aria-modal', 'false')
  await expect(dialog.getByRole('heading', { name: 'Linha 1–Azul' })).toBeVisible()
  const mobile = testInfo.project.name !== 'desktop'
  if (mobile) {
    await expect(page.getByRole('region', { name: 'Percurso da linha' })).toBeHidden()
    await page.screenshot({ path: testInfo.outputPath('painel-compacto.png') })
    await page.getByRole('button', { name: 'Ver detalhes', exact: true }).click()
  }
  const route = page.getByRole('region', { name: 'Percurso da linha' })
  await expect(route).toBeVisible()
  await expect(route.getByRole('button', { name: 'Ver estação Sé', exact: true })).toContainText('3')
  await expect(route.getByRole('button', { name: 'Ver estação Paraíso', exact: true })).toContainText('2')
  await expect(route.getByRole('button', { name: 'Ver estação São Bento', exact: true })).toContainText('Previstas')
  await page.screenshot({ path: testInfo.outputPath('percurso.png') })
  const headings = await dialog.locator('h3').allTextContents()
  expect(headings.indexOf('Estações')).toBeLessThan(headings.indexOf('Notícias'))
  await route.getByRole('button', { name: 'Ver estação Sé', exact: true }).click()
  await expect(dialog.getByRole('heading', { name: 'Sé', exact: true })).toBeVisible()
  const primaryMap = testInfo.project.name === 'iphone' ? 'Abrir no Apple Maps' : 'Abrir no Google Maps'
  await expect(dialog.getByRole('link', { name: primaryMap })).toBeVisible()
  await expect(dialog.getByRole('link', { name: primaryMap })).toHaveAttribute('href', /maps/)
  await expect(dialog.getByRole('button', { name: /3.*Vermelha/ })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('estacao.png') })
  await dialog.getByRole('button', { name: /3.*Vermelha/ }).click()
  await expect(dialog.getByRole('heading', { name: 'Linha 3–Vermelha' })).toBeVisible()
  if (mobile) await expect(page.getByRole('button', { name: 'Ver detalhes', exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(dialog).toHaveCount(0)
})

test('painel mantém leitura no tema escuro e puxador expande e recolhe', async ({ page }, testInfo) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Exibição', exact: true }).click()
  await page.getByRole('button', { name: /Tema escuro/ }).click()
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'Diagrama', exact: true }).click()
  await page.getByRole('button', { name: 'Linhas', exact: true }).click()
  await page.getByRole('button', { name: /^2 Verde/ }).click()
  const dialog = page.getByRole('dialog')
  if (testInfo.project.name !== 'desktop') {
    const compact = await dialog.boundingBox()
    const handle = page.getByRole('button', { name: 'Expandir painel', exact: true })
    const start = await handle.boundingBox()
    await page.mouse.move(start!.x + start!.width / 2, start!.y + start!.height / 2)
    await page.mouse.down()
    await page.mouse.move(start!.x + start!.width / 2, start!.y - 80, { steps: 5 })
    await page.mouse.up()
    await expect(page.getByRole('button', { name: 'Recolher painel', exact: true })).toHaveAttribute('aria-expanded', 'true')
    expect((await dialog.boundingBox())!.height).toBeGreaterThan(compact!.height)
    await page.screenshot({ path: testInfo.outputPath('painel-escuro-expandido.png') })
    const expandedHandle = await page.getByRole('button', { name: 'Recolher painel', exact: true }).boundingBox()
    await page.mouse.move(expandedHandle!.x + 30, expandedHandle!.y + 15)
    await page.mouse.down()
    await page.mouse.move(expandedHandle!.x + 30, expandedHandle!.y + 100, { steps: 5 })
    await page.mouse.up()
    await expect(page.getByRole('button', { name: 'Expandir painel', exact: true })).toHaveAttribute('aria-expanded', 'false')
    // Button/keyboard activation provides an alternative to dragging.
    await page.getByRole('button', { name: 'Expandir painel', exact: true }).focus()
    await page.keyboard.press('Enter')
    await expect(page.getByRole('button', { name: 'Recolher painel', exact: true })).toBeVisible()
  } else {
    await page.screenshot({ path: testInfo.outputPath('painel-escuro-desktop.png') })
  }
  await expect(page.locator('body')).toHaveJSProperty('scrollWidth', testInfo.project.use.viewport!.width)
  await dialog.getByRole('button', { name: 'Fechar', exact: true }).click()
  await expect(dialog).toHaveCount(0)
})
